// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6Final.Models;

namespace Mission6Final.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230425022938_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6Final.Models.AddMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            director = "bill",
                            edited = false,
                            lentTo = "none",
                            notes = "none",
                            rating = "ten",
                            title = "Lion King",
                            year = 2000
                        },
                        new
                        {
                            MovieId = 2,
                            director = "Nemo",
                            edited = false,
                            lentTo = "none",
                            notes = "none",
                            rating = "9",
                            title = "Finding Nemo",
                            year = 2000
                        },
                        new
                        {
                            MovieId = 3,
                            director = "Obi",
                            edited = false,
                            lentTo = "none",
                            notes = "none",
                            rating = "ten",
                            title = "Star Wars",
                            year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
